# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb78a187296694cb4c3348a97f65569c7642e0a728fd41ffe441941058fd690f9a27017bd20006071a953c20b6ca836ff64af57482590b74fdc35900178aae7e

test:
  secret_key_base: f15dbcce71dad5bbb768711931177bd0803a8eb8ecf8609a9fabb523f5d2fdd0317ba8375a6bfc301221bd7aef68208818981172ab689f1f3da3a5c0d7c2a444

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
